CREATE TABLE User (
	_id INT NOT NULL AUTO_INCREMENT,
	userName VARCHAR(30) NOT NULL UNIQUE,
	displayName VARCHAR(30) NOT NULL UNIQUE,
	password VARCHAR(15) NOT NULL,
	currentlyActive TINYINT(1) NOT NULL,

	PRIMARY KEY (_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
